Programming Task
1. Dominant Value Function: Create a function in Python that calculates and returns the dominant value (eigenvalue with the largest magnitude) of a given matrix.
2. Inverse Matrix: Use the dominant value function to assist in writing a function that calculates the inverse of a given matrix.
3. Identity Matrix Function: Create a function in Python that calculates and returns the identity matrix of the same dimension as the given matrix.


In [1]:
import numpy as np 
def CreateArray ():
    # the use of this funtion is to create 3 arrays with 3 random elements with a range from 1 to 10 
    # and merge the 3 array and then return 3 by 3 array 
    array1=np.random.randint(1,10,3)
    array2=np.random.randint(1,10,3)
    array3=np.random.randint(1,10,3)
    return np.array([array1,array2,array3])

def EigenValue(matrix):
    #this funtion generates the eigenvalue of the matrix passed and then get the max of the eigenvalues 
    return np.linalg.eig(matrix)[0].max()

def MatrixInverse (matrix):
    #this funtion return the inverse of the matrix passed
    return np.linalg.inv(matrix)

def IdentityMatrix (InverseMatrix,matrix):
    #this funtion returns the dot multplication of the matrix and its inverse which should be identity matrix 
    return np.dot(InverseMatrix,matrix)
    

matrix=CreateArray()
InverseMatrix=MatrixInverse(matrix)
IdentityMatrix=IdentityMatrix(InverseMatrix,matrix)
print(IdentityMatrix)


[[ 1.00000000e+00  5.55111512e-17  1.66533454e-16]
 [ 2.22044605e-16  1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
